spring:
  datasource:
    url: jdbc:mysql://localhost:3306/routdoo?serverTimezone=UTC&characterEncoding=UTF-8
    username: routdoo
    password: routdoo
    driver-class-name: com.mysql.cj.jdbc.Driver
 
  jpa:
    open-in-view: false # OSIV 성능 최적화를 위한 false 처리 영속성 컨텍스트 와 db 커넥션의 범위를 조정하여 리소스 낭비를 줄임
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size : 500  ## 컬렉션 조회 최적화를 위한 설정
        
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

logging:
  config: classpath:log4j2.yml
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace  
