# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]

jobs:
  Deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Gradle 권한 부여
    - name: Grant permission for gradlew
      run: chmod +x ./gradlew

    # 테스트 및 빌드
    - name: Build with Gradle
      run: ./gradlew clean bootJar
      
    - run: ls
    - run: ls build
    - run: ls build/libs


    - name: Docker build
      uses: docker/build-push-action@v3.2.0
      with:
          context: .
          file: ./Dockerfile
          push: false
          tags: dailyroutine:latest
    - run: /usr/bin/docker save -o dailyroutine.tar dailyroutine:latest

      # tar 파일 권한 수정
    - name: Set permission for tar file
      run: chmod 644 dailyRoutine.tar

    - name: Send docker image file to test server
      uses: appleboy/scp-action@master
      with:
        host: "210.89.190.40"
        username: ${{ secrets.POSTOFFICE_NAME }} # dailyroutine
        password : ${{ secrets.POSTOFFICE_PASS }} # daily!23
        port: 7022
        source: "dailyroutine.tar"
        target: "/home/dailyroutine/versions"


    - name: Bootup server
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: "210.89.190.40"
        user: ${{ secrets.POSTOFFICE_NAME }}  # dailyroutine
        pass: ${{ secrets.POSTOFFICE_PASS }} # daily!23
        port: 7022
        connect_timeout: 10s
        first_ssh: |
          docker stop dailyroutine-test || true
          docker rm dailyroutine-test || true
          docker image rm dailyroutine:latest || true
          docker load -i /home/postoffice/dailyroutine/dailyroutine.tar
          docker run -d -p 32468:8080 --name dailyroutine-test dailyroutine:latest
